name: Ga2O3_Mg
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - matplotlib
  - ipykernel
  - jupyter
  - pymatgen
  - ase
prefix: /Volumes/Data/conda/miniconda3/envs/Ga2O3_Mg
